export const items =  [
    {
      id: 1,
      category: 'Juventes',
      title: "Juventes 23/24",
      imgSrc: '/assets/images/fv1.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Juventes Away jersey 23/24',
      price: '850',
    },
    {
      id: 2,
      category: 'Real Madrid',
      title: "Real Madrid 23/24",
      imgSrc: '/assets/images/fv2.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Real Madrid Home 23/24',
      price: '700',
    },
    {
      id: 3,
      category: 'Barcelona',
      title: "Barcelona 23/24",
      imgSrc: '/assets/images/fv3.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Barcelona Home 23/24',
      price: '800',
    },
    {
      id: 4,
      category: 'Mancity',
      title: "Manchester City 23/24",
      imgSrc: '/assets/images/fv4.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Manchester City Home 23/24',
      price: '750',
    },
    {
      id: 5,
      category: 'lfc',
      title: "Liverpool FC",
      imgSrc: '/assets/images/fv5.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'LiverPool FC home 23/24',
      price: '650',
    },
    {
      id: 6,
      category: 'chelsea',
      title: "Chelsea FC",
      imgSrc: '/assets/images/fv6.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Chelsea away 23/24',
      price: '700',
    },
    {
      id: 7,
      category: 'Arsenal',
      title: "Arsenal",
      imgSrc: '/assets/images/fv7.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Arsenal home 23/24',
      price: '700',
    },
    {
      id: 8,
      category: 'Dortmund',
      title: "Dortmund",
      imgSrc: '/assets/images/fv8.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Dortmund away 23/24',
      price: '800',
    },
    {
      id: 9,
      category: 'intermiami',
      title: "InterMiami ",
      imgSrc: '/assets/images/fv9.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Intermiami Home 23/24',
      price: '1000',
    },
    {
      id: 10,
      category: 'Bayern',
      title: "Bayern FC",
      imgSrc: '/assets/images/fv10.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Bayern FC Home 23/24',
      price: '600',
    },
    {
      id: 11,
      category: 'Manu',
      title: "Manchester United Fc home 23/24",
      imgSrc: '/assets/images/fv11.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: '',
      price: '850',
    },
    {
      id: 12,
      category: 'Psg',
      title: "PSG",
      imgSrc: '/assets/images/fv12.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'PSG 23/24',
      price: '900',
    },
    {
      id: 13,
      category: 'alhilal',
      title: "Al-HILAL",
      imgSrc: '/assets/images/fv13.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'AL-HILAL Home 23/24',
      price: '900',
    },
    {
      id: 14,
      category: 'Argentina',
      title: "Argentina FC",
      imgSrc: '/assets/images/fv14.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Argentina FC 23/24',
      price: '1000',
    },
    {
      id: 15,
      category: 'alnassr',
      title: "AL-NASSR",
      imgSrc: '/assets/images/fv15.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'AL-NASSR Home 23/24',
      price: '1000',
    },
    {
      id: 16,
      category: 'Real Madrid',
      title: "Real Madrid 24",
      imgSrc: '/assets/images/fv16.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Real Madrid away 23/24',
      price: '1000',
    },
    {
      id: 17,
      category: 'Real Madrid',
      title: "Real Madrid 23/24",
      imgSrc: '/assets/images/fv17.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Real Madrid Third 23/24',
      price: '1000',
    },

    {
      id: 18,
      category: 'lfc',
      title: "Liverpool FC",
      imgSrc: '/assets/images/fv18.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'LiverPool FC Away 23/24',
      price: '700',
    },
    
  ]